// +build generate

package main

import (
	"bytes"
	"crypto/x509"
	"encoding/pem"
	"fmt"
	"net/http"
	"os"
	"path"
	"runtime"
	"sort"
	"strings"
	"text/template"
	"time"

	. "github.com/dave/jennifer/jen"
	"golang.org/x/net/html"
)

const (
	RC_URL = "https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/regions-certs.html"
)

type readmeInfo struct {
	Certificates []readmeCertInfo
}

type readmeCertInfo struct {
	Region    string
	NotAfter  time.Time
}

func main() {
	_, ourFile, _, _ := runtime.Caller(0)
        parentDir := path.Join(path.Dir(ourFile), "..")

	regionList, expiryMap := refreshCertificates(parentDir)
	refreshReadme(ourFile, parentDir, regionList, expiryMap)
}

func refreshCertificates(parentDir string) ([]string, map[string]string) {
	f, err := os.Create(path.Join(parentDir, "regioncert_gen.go"))
	if err != nil {
		panic(err)
	}

	j := NewFile("awsregioncertificates")
	j.HeaderComment("Code generated by robots, DO NOT EDIT.")

	resp, err := http.Get(RC_URL)
	if err != nil {
		panic(err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		panic(fmt.Sprintf("bad http status %d", resp.StatusCode))
	}

	var region string
	var wantText bool
	regionCertMap := make(map[string]string)
	tokenizer := html.NewTokenizer(resp.Body)
	for {
		tt:= tokenizer.Next()
		if tt == html.ErrorToken {
			break
		}
		if tt == html.StartTagToken {
			token := tokenizer.Token()
			if token.Data == "awsui-expandable-section" {
				for _, attr := range token.Attr {
					if attr.Key == "id" {
						region = strings.TrimSuffix(attr.Val, "-cert")
						break
					}
				}
			}
			if token.Data == "dd" {
				for _, attr := range token.Attr {
					if attr.Key == "tab-id" && attr.Val == "rsa" {
						wantText = true
						break
					}
				}
			}
		}
		if tt == html.TextToken && wantText {
			token := tokenizer.Token()
			regionCertMap[region] = strings.TrimSuffix(
				strings.ReplaceAll(token.String(), "\t", ""), "\n")
			wantText = false
		}
	}

	d := make(Dict)
	ops := make([]Code, len(regionCertMap))
	i := 0
	regionList := make([]string, len(regionCertMap))
	for region := range regionCertMap {
		regionList[i] = region
		i++
	}
	sort.Strings(regionList)
	i = 0
	for _, region := range regionList {
		cert := regionCertMap[region]
		constName := strings.Replace(region, "-", "_", -1) + "_cert"
		ops[i] = Id(constName).Op("=").Lit(cert)
		i++
		d[Lit(region)] = Id(constName)
	}
	j.Const().Defs(ops...)

	j.Func().Id("getRegionCertStrings").Params().Map(String()).String().Block(
		Return(Map(String()).String().Values(d)),
	)

	fmt.Fprintln(f, fmt.Sprintf("%#v", j))

	err = f.Close()
	if err != nil {
		panic(err)
	}

	return regionList, regionCertMap
}

func refreshReadme(ourFile string, parentDir string, regionList []string, certMap map[string]string) {
	now := time.Now()
	expiryMap := make(map[string]time.Time, len(certMap))
	for region, certStr := range certMap {
		block, _ := pem.Decode([]byte(certStr))
		if block == nil {
			panic(fmt.Sprintf("failed to parse PEM block for region %s", region))
		}
		cert, err := x509.ParseCertificate(block.Bytes)
		if err != nil {
			panic(err)
		}
		expiryMap[region] = cert.NotAfter
		if now.Before(cert.NotBefore) {
			panic(fmt.Sprintf("certificate for %s is not valid yet: %v", region, cert.NotBefore))
		}
	}

	data := readmeInfo{}
	data.Certificates = make([]readmeCertInfo, len(expiryMap))
	i := 0
	for _, region := range regionList {
		data.Certificates[i] = readmeCertInfo{
			Region: region,
			NotAfter: expiryMap[region],
		}
		i++
	}

	tmplPath := path.Join(path.Dir(ourFile), "README.md.tmpl")
	tmplContent, err := os.ReadFile(tmplPath)
	if err != nil {
		panic(err)
	}

	tmpl, err := template.New("README.md.tmpl").Parse(string(tmplContent))
	if err != nil {
		panic(err)
	}

	var buf bytes.Buffer
	err = tmpl.Execute(&buf, data)
	if err != nil {
		panic(err)
	}

	readmePath := path.Join(parentDir, "README.md")
	err = os.WriteFile(readmePath, buf.Bytes(), 0644)
	if err != nil {
		panic(err)
	}
}
