name: generate_test

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_call:
  pull_request:
  push:
    branches:
      - main

jobs:
  check_generate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.4'

      - name: Run go generate
        run: go generate ./...

      - name: Check diff
        run: git diff --quiet . || (git --no-pager diff . && exit 1 || exit 1)
